### ISSUE TITLE
CompositeConnectionDetails not updating the secret

### ISSUE THREAD

**Issue by ecoupal-believe** [crossplane-contrib/function-go-templating#100]
### What happened?

The secret generated by CompositeConnectionDetails does not contain the expected values.

### How can we reproduce it?

Here is the template:

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-inline
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: confluent.crossplane.io/v1alpha1
            kind: APIKey
            metadata:
              annotations:
                {{ setResourceNameAnnotation "apikey" }}
              name: apikey
            spec:
              forProvider:
                displayName: app-manager-kafka-api-key
                owner:
                  - id: XXX
                    apiVersion: XXX
                    kind: XX
                managedResource:
                - apiVersion: XXX
                  environment:
                    - id: XXX
                  id: XXX
                  kind: XXX
              writeConnectionSecretToRef:
                name: some-secret
                namespace: crossplane-system
            ---
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            {{ if eq (.observed.resources.apikey | getResourceCondition "Ready").Status "True" }}
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            data:
              url: {{ "http://www.example.com" | b64enc }}
            {{ - end }}
    - step: ready
      functionRef:
        name: auto-ready
```

### Actual result:
```
apiVersion: v1
kind: Secret
metadata:
  name: some-secret
  namespace: crossplane-system
  ownerReferences:
    - apiVersion: confluent.crossplane.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: APIKey
      name: apikey
      uid: eaf71aa1-a799-4448-8030-2e093bee6a7c
type: connection.crossplane.io/v1alpha1
data:
  api_key_id: XXX
  api_key_secret: XXX
  attribute.secret: XXX
```

### Expected result:
```
apiVersion: v1
kind: Secret
metadata:
  name: some-secret
  namespace: crossplane-system
  ownerReferences:
    - apiVersion: confluent.crossplane.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: APIKey
      name: apikey
      uid: eaf71aa1-a799-4448-8030-2e093bee6a7c
type: connection.crossplane.io/v1alpha1
data:
  url: aHR0cDovL3d3dy5leGFtcGxlLmNvbQ==
```

I don't see any error and the secret is just not updated no matter what I put inside data. 

Any idea what's happening ?

Could it be related to the confluent provider I use ? https://github.com/crossplane-contrib/provider-confluent

Thanks

### What environment did it happen in?
Kubernetes: GKE 1.28.8-gke.1095000
Function version: 0.4.1
Crossplane: 1.15.1

**Comment by ecoupal-believe** [comment]
This is not a provider issue, I'm also struggling with this one:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-inline
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: cloudplatform.gcp.upbound.io/v1beta1
            kind: ServiceAccount
            metadata:
              annotations:
                {{ setResourceNameAnnotation "sa" }}
              labels:
                testing.upbound.io/example-name: example-service-account-key
              name: example-service-account-key
            spec:
              forProvider:
                displayName: Used for example service account key testing
            ---
            apiVersion: cloudplatform.gcp.upbound.io/v1beta1
            kind: ServiceAccountKey
            metadata:
              annotations:
                {{ setResourceNameAnnotation "key" }}
              name: example-service-account-key
            spec:
              forProvider:
                publicKeyType: TYPE_X509_PEM_FILE
                serviceAccountIdSelector:
                  matchLabels:
                    testing.upbound.io/example-name: example-service-account-key
            ---
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            data:
              url: {{ "http://www.example.com" | b64enc }}
            {{ end }}
    - step: ready
      functionRef:
        name: auto-ready
```
I must be missing something...
