### ISSUE TITLE
Enhancement: Support Multiple Inline Templates

### ISSUE THREAD

**Issue by organic-scholar** [crossplane-contrib/function-go-templating#104]
### What problem are you facing?
The inline definition of resources using `source: Inline` can become unmaintainable as the template size grows. The solution to the problem of increasing size of the inline template is to use `source: FileSystem` for which you can construct a config map and mount it to the function using `DeploymentRuntimeConfig` but that has another problem for each different composition template, you have to deploy a copy of the function.

### Change proposed to help solve the problem?
Using `source: Inline` if there is a new field `inline.templates` is introduced of type `[]string` that can have multiple yaml strings for resource definitions then kustomize can be used to separate resource definitions into separate files e.g

```yaml
# composition.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-inline
spec:
  mode: Pipeline
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          templates: []
```

```yaml
# user.patch.yaml
- op: add
  path: /spec/pipeline/0/input/inline/templates/-
  value: |
    apiVersion: iam.aws.upbound.io/v1beta1
    kind: User
    metadata:
      annotations:
        gotemplating.fn.crossplane.io/composition-resource-name: user
    spec:
      forProvider: {}

```

```yaml
# access-key.patch.yaml
- op: add
  path: /spec/pipeline/0/input/inline/templates/-
  value: |
    apiVersion: iam.aws.upbound.io/v1beta1
    kind: AccessKey
    metadata:
      annotations:
        gotemplating.fn.crossplane.io/composition-resource-name: access-key
    spec:
      forProvider: {}
```

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - compositions.yaml
patches:
  - path: user.patch.yaml
    target: { kind: Composition, name: example-inline }
  - path: access-key.patch.yaml
    target: { kind: Composition, name: example-inline }
```

### Implementation
Adding this new field to `TemplateSourceInline` will be backwards compatible.

```go
type TemplateSourceInline struct {
	Template  string   `json:"template,omitempty"`
	Templates []string `json:"templates,omitempty"`
}
```

The `string` items of `Templates` field will be appended to the `Template` field with separator `"\n---\n"`
