### ISSUE TITLE
Can't retrieve atProvider of observe-only resource

### ISSUE THREAD

**Issue by mcanevet** [crossplane-contrib/function-go-templating#120]
### What happened?

Somehow the `$.observed.resources.<my-resource>.resource.status.atProvider` of a observe-only resource is empty.

### How can we reproduce it?

```yaml
---
apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: Stack
metadata:
  annotations:
    {{ setResourceNameAnnotation "stack" }}
    crossplane.io/external-name: {{ $.observed.composite.resource.metadata.name }}
spec:
  forProvider: {}
  managementPolicies: ["Observe"]

---
apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: AccessPolicy
metadata:
  annotations:
    {{ setResourceNameAnnotation "accessPolicy" }}
    debug: |
      {{ toJson $.observed.resources.stack.resource.status }}
spec:
  forProvider:
    name: metric-publisher-for-sm
    realm:
      - type: stack
        identifier: {{ $.observed.resources.stack.resource.status.atProvider.id }}
    region: {{ $.observed.resources.stack.resource.status.atProvider.regionSlug }}
    scopes: ["metrics:write", "stacks:read", "logs:write", "traces:write"]
```

I get this result:
```yaml
apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: AccessPolicy
metadata:
  annotations:
    debug: >
      {"atProvider":{},"conditions":[{"lastTransitionTime":"2024-09-05T09:57:38Z","reason":"ReconcileSuccess","status":"True","type":"Synced"}]}
spec:
  ...
```

I was expecting to be able to retrieve the attributes of my observed-only resource

### What environment did it happen in?
Function version: `v0.6.0`
