### ISSUE TITLE
Support creating composed resources with the composite resource's type (recursion)

### ISSUE THREAD

**Issue by vilmosmartinek** [crossplane-contrib/function-go-templating#127]
## What problem are you facing?

In our solution in some cases we are using a wrapper composition on top of the real composition. This approach helps with combining fields both from envconfigs and composite fields. An example:

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-wrapper # defining the wrapper composition
spec:
  mode: Pipeline
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: XExample
  pipeline:

  - step: example
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
        - name: example
          base:
            apiVersion: example.com/v1alpha1
            kind: XExample
            spec:
              compositionRef:
                name: example-real # instantiating the real composition
          patches:
            # omitted for brevity
            
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready
```

However, this approach does not work with `function-go-templating`, because it does not render this resource as a *composed resource*, only updates the status fields of the *composite resource*.

## How could this Function help solve your problem?

To leave the current _status updating_ feature unchanged and also support our use-case, we could specify a new meta annotation (e.g. `gotemplating.fn.crossplane.io/allow-recursion`) that modifies the current functionality and lets the function generate composed resources of the composite resource's type.

An example composition would look like this:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-inline
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- range $i := until ( .observed.composite.resource.spec.count | int ) }}
            ---
            apiVersion: example.crossplane.io/v1beta1
            kind: XR
            metadata:
              annotations:
                "gotemplating.fn.crossplane.io/allow-recursion": "true" # <-- this is the new meta annotation
                {{ setResourceNameAnnotation (print "test-xr-" $i) }}
            {{ end }}
```

The output after rendering this with `crossplane beta trace` (`count` equals **2**):

```yaml
---
apiVersion: example.crossplane.io/v1beta1
kind: XR
metadata:
  name: example
status:
  conditions:
  - lastTransitionTime: "2024-01-01T00:00:00Z"
    message: 'Unready resources: test-xr-0, test-xr-1'
    reason: Creating
    status: "False"
    type: Ready
---
apiVersion: example.crossplane.io/v1beta1
kind: XR
metadata:
  annotations:
    crossplane.io/composition-resource-name: test-xr-0
  generateName: example-
  labels:
    crossplane.io/composite: example
  ownerReferences:
  - apiVersion: example.crossplane.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: XR
    name: example
    uid: ""
---
apiVersion: example.crossplane.io/v1beta1
kind: XR
metadata:
  annotations:
    crossplane.io/composition-resource-name: test-xr-1
  generateName: example-
  labels:
    crossplane.io/composite: example
  ownerReferences:
  - apiVersion: example.crossplane.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: XR
    name: example
    uid: ""
```

I already have a POC working, so if you think this solution makes sense, I can create a PR for it. Thank you very much for your consideration!
