### ISSUE TITLE
Get the root context within loops

### ISSUE THREAD

**Issue by twobiers** [crossplane-contrib/function-go-templating#142]
### What problem are you facing?
When using `range` loops, the dot `.` is overriden by the loop item, so functions like `getComposedResource` do not work anymore as documented.

Here is an example:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-function-get-composed-resource
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            {{ $flexServerResourceName := "flexServer" }}
            # Create an initial composed resource for which we will retrieve a value
            apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
            kind: FlexibleServer
            metadata:
              annotations:
                {{ setResourceNameAnnotation $flexServerResourceName }}
                gotemplating.fn.crossplane.io/ready: "False"
            spec:
              forProvider:
                storageMb: 32768
              providerConfigRef:
                name: my-provider-cfg
            ---
            {{ $i, $item := range [1, 2, 3] }}
            # Here we could use `$` instead of `.`
            {{ $flexServer := getComposedResource . $flexServerResourceName }}            
            apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
            kind: FlexibleServerConfiguration
            metadata:
              annotations:
                {{ setResourceNameAnnotation "flexServerConfig" }}
                gotemplating.fn.crossplane.io/ready: "False"
              name: {{ printf "config-%s" $i }}
            spec:
              forProvider:
                # Populate the field using the observed status of the retrieved resource
                serverId: {{ get $flexServer.status "id" }}
              providerConfigRef:
                name: my-provider-cfg
            {{ end }}
```

### How could this Function help solve your problem?
Helm solves that by adding `$` variable: https://helm.sh/docs/chart_template_guide/variables/#helm
