### ISSUE TITLE
Support providing Go templates as OCI images

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane-contrib/function-go-templating#24]
### What problem are you facing?

Currently, the function can get template inputs as inline or from a file system directory. As a next step, we can support getting them from OCI images. In this way, users may easily decide which version of the templates to use in their composition.

### How could this Function help solve your problem?

Following API is suggested by @turkenh in the [comment](https://github.com/crossplane/crossplane/pull/4935#discussion_r1391039696):

```
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Image
        image:
          repo: turkenh/my-templates
          tag: v0.1.0
```
In this case, templates are expected in a fixed path like `/templates`.
