### ISSUE TITLE
Add a helper function for `setName`

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane-contrib/function-go-templating#26]
### What problem are you facing?

function-go-templating requires a special annotation `gotemplating.fn.crossplane.io/composition-resource-name` in the resource manifests to identify composed resources. Instead of writing the annotation, we may simply define a helper function and use it in our templates. 

### How could this Function help solve your problem?

Define `setName` helper function with the input `name` as a string to set the required annotation.

```
apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    {{ setName "my-user" }}
  labels:
    testing.upbound.io/example-name: my-user
spec:
  forProvider: {}
```
