### ISSUE TITLE
ExtraResources kind does not produce any debugging info during run

### ISSUE THREAD

**Issue by artisticcheese** [crossplane-contrib/function-go-templating#425]
### What happened?
Debug output is not being provided for ExtraResources kind

### How can we reproduce it?
```
  mode: Pipeline
  pipeline:
    - step: pull-extra-resources-gotemplate
      functionRef:
        name: function-go-templating
      input:
        apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
        kind: ExtraResources
        requirements:
          some-foo-by-name:
            # Resources can be requested either by name
            apiVersion: example.com/v1beta1
            kind: Pod
            matchName: "some-extra-foo"
          some-foo-by-labels:
            # Or by label.
            apiVersion: example.com/v1beta1
            kind: API
            matchLabels:
              claim-namespace: crossplane-demo
```
Function config
```
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: artifactory.play.intapp.com/devops-docker-upstreams-prod/crossplane-contrib/function-go-templating:v0.10.0
  runtimeConfigRef:
    name: enable-debug-function
--- 
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: enable-debug-function
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              args:
                - --debug
```
Output of function does not produce any debug information 
```
2025-05-21T17:29:59.777Z	INFO	fn/fn.go:56	Running Function	{"tag": ""}
2025-05-21T17:30:29.702Z	INFO	fn/fn.go:56	Running Function	{"tag": ""}
2025-05-21T17:30:29.728Z	INFO	fn/fn.go:56	Running Function	{"tag": ""}
2025-05-21T17:30:29.750Z	INFO	fn/fn.go:56	Running Function	{"tag": ""}
2025-05-21T17:30:59.727Z	INFO	fn/fn.go:56	Running Function	{"tag": ""}
2025-05-21T17:31:29.739Z	INFO	fn/fn.go:56	Running Function	{"tag": ""}
2025-05-21T17:31:59.752Z	INFO	fn/fn.go:56	Running Function	{"tag": ""}
```

### What environment did it happen in?
Function version: 0.10.0
