### ISSUE TITLE
Can't patch XR metadata

### ISSUE THREAD

**Issue by ytsarev** [crossplane-contrib/function-go-templating#76]
### What happened?

Status propagation works
```
            apiVersion: example.crossplane.io/v1beta1
            kind: XR
            status:
              dummy: cool-status
```

But metadata propagation does not.
```
            ---
            apiVersion: example.crossplane.io/v1beta1
            kind: XR
            metadata:
                 annotation:
                     cool: annotation
```

### How can we reproduce it?

Try to set custom annotation for XR as in the example above.

### What environment did it happen in?
Function version:  v0.4.1
