### ISSUE TITLE
Unable to decode array items that are more complex than a simple list

### ISSUE THREAD

**Issue by humoflife** [crossplane-contrib/function-go-templating#91]
### What happened?

Receiving the following `crossplane beta render error`:

```
error converting YAML to JSON: yaml: line 7: did not find expected ',' or ']'
```

XR:

```
apiVersion: dynamodb.aws.platform.upbound.io/v1alpha1
kind: Instance
metadata:
  name: go-template-debug
spec:
  parameters:
    array:
      - name: Tester-1
        type: Diligent
      - name: Tester-2
        type: More Diligent
```

function-go-templating debug output:

```
2024-05-01T20:58:57.868-0700	DEBUG	function-go-templating/fn.go:96	rendered manifests	{"manifests": "\n---\napiVersion: dynamodb.aws.upbound.io/v1beta1\nkind: Table\nmetadata:\n  annotations:\n    gotemplating.fn.crossplane.io/composition-resource-name: table\nspec:\n  forProvider:\n    array: [map[name:Tester-1 type:Diligent] map[name:Tester-2 type:More Diligent]]\n"}
```

Composition is as follows. Note that the issue has nothing to do with the Kind and api version but was first noticed through a DynamoDB table with an attribute and a globalSecondaryIndex that neither were properly decoded from YAML to JSON by function-go-templating:

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: table.dynamodb.aws.platform.upbound.io
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: dynamodb.aws.platform.upbound.io/v1alpha1
    kind: XTable

  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $parameters := .observed.composite.resource.spec.parameters }}
            ---
            apiVersion: dynamodb.aws.upbound.io/v1beta1
            kind: Table
            metadata:
              annotations:
                {{ setResourceNameAnnotation (print "table") }}
            spec:
              forProvider:
                array: {{ $parameters.array }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
```

### How can we reproduce it?

crossplane beta render xr.yaml composition.yaml function.yaml

The function.yaml is as follows:

```
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
  annotations:
    render.crossplane.io/runtime: Development
spec:
  package: function-go-templating
  packagePullPolicy: Always
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: crossplane-contrib-function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1
```

### What environment did it happen in?
Function version: v0.4.1

* Cloud provider or hardware configuration
* Kubernetes version (use `kubectl version`): v1.29.1
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift). Render without cluster, but also on EKS.
* OS (e.g. from /etc/os-release): MaxOSX
* Kernel (e.g. `uname -a`): Darwin Kernel Version 22.6.0

**Comment by haarchri** [comment]
something like this is working:

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: table.dynamodb.aws.platform.upbound.io
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: dynamodb.aws.platform.upbound.io/v1alpha1
    kind: XTable

  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $spec := .observed.composite.resource.spec }}
            ---
            apiVersion: dynamodb.aws.upbound.io/v1beta1
            kind: Table
            metadata:
              annotations:
                {{ setResourceNameAnnotation (print "table") }}
            spec:
              forProvider:
                array:
                {{- range $i, $array := $spec.parameters.array }}
                  - name: {{ $array.name }}
                    type: {{ $array.type }}
                {{- end }}


    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
```

**Comment by phisco** [comment]
It should also work using `toYAML`

**Comment by humoflife** [comment]
The above decoding behavior is be design. To use function-go-templating to perform the array assignment, one can use the following syntax. 
```

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: table.dynamodb.aws.platform.upbound.io
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: dynamodb.aws.platform.upbound.io/v1alpha1
    kind: XTable

  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $spec := .observed.composite.resource.spec }}
            ---
            apiVersion: dynamodb.aws.upbound.io/v1beta1
            kind: Table
            metadata:
              annotations:
                {{ setResourceNameAnnotation (print "table") }}
            spec:
              forProvider:
                array:
                {{- range $i, $array := $spec.parameters.array }}
                  - name: {{ $array.name }}
                    {{- if $array.type }}
                    type: {{ $array.type }}
                    {{- end }}
                {{- end }}
```
