### ISSUE TITLE
Missing managed resource result

### ISSUE THREAD

**Issue by laseanb** [crossplane-contrib/function-go-templating#92]
### What happened?

I want to make a queue and a dead letter queue but I need the ARN from the queue to supply for the redriveAllowPolicy in the dead letter queue. After following the advice from this [issue](https://github.com/crossplane-contrib/function-go-templating/issues/79) to ref another managed resource, I'm finding that `.observed.resources` doesn't contain the queue resource in order to fill in the ARN field for the dead letter queue - and results in the error:
```sh
cannot compose resources: pipeline step "render-templates-1" returned a fatal result: cannot execute template: template: manifests:28:16: executing "manifests" at <dig "resource" "status" "atProvider" "arn" "" $queueManagedResource>: error calling dig: interface conversion: interface {} is string, not map[string]interface {}
```
Any advice?

### How can we reproduce it?

```yml
- step: render-templates
  functionRef:
    name: function-go-templating
  input:
    apiVersion: gotemplate.fn.crossplane.io/v1beta1
    kind: GoTemplate
    source: Inline
    inline:
      template: |
        ---
        {{ $claim := .observed.composite.resource.spec }}

        apiVersion: sqs.aws.upbound.io/v1beta1
        kind: Queue
        metadata:
           name: dev-{{ $claim.name }} 
           annotations:
             {{ setResourceNameAnnotation (print "dev-" $claim.name) }}
        spec:
           forProvider:
             name: dev-{{ $claim.name }} 
             region: us-west-1
        ---
        {{ $claim := .observed.composite.resource.spec }}
        {{ $queuefullname := printf "dev-%s" $claim.name }}
        {{ $queueManagedResource := get .observed.resources "$queuefullname" }}
        {{ $queueARN := dig "resource" "status" "atProvider" "arn" "" $queueManagedResource }}

        apiVersion: sqs.aws.upbound.io/v1beta1
        kind: Queue
        metadata:
           name: dev-dlq-{{ $claim.queue }} 
           annotations:
             {{ setResourceNameAnnotation (print "dev-dlq-" $claim.queue) }}
        spec:
           forProvider:
             name: dev-dlq-{{ $claim.queue }} 
             region: us-west-1
             redriveAllowPolicy: '{"redrivePermission" = "byQueue", "sourceQueueArns" = ["{{ $queueARN }}"]}'
- step: ready
  functionRef:
    name: function-auto-ready
```
### What environment did it happen in?
Function version: v0.4.1

* Crossplane v1.15.2 with provider-aws-sqs v1.2.1
* Kubernetes: v1.27.10+rke2r1
