### ISSUE TITLE
Ability to grab the namespace off the claim

### ISSUE THREAD

**Issue by silverbp** [crossplane-contrib/function-go-templating#97]
### What problem are you facing?
Trying to figure out how I can get the namespace off the claim to be able to provision resources in the provider using the name of the namespace in the name.

### How could this Function help solve your problem?
Is there a way to pull metadata properties from the claim, specifically the namespace using go-templating or do I need to take the namespace as a parameter?

**Comment by jaylevin** [comment]
You can grab the claim namespace from the XR's `crossplane.io/claim-namespace` label.

Here's an example of creating an `EnvironmentConfig` resource with a `claim_namespace` key equal to the namespace the claim was deployed to.

```yaml
{{ $claimNamespace := index $.observed.composite.resource.metadata.labels "crossplane.io/claim-namespace" }}

---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: test
data:
  claim_namespace: {{ $claimNamespace }}
---
```
